#!/bin/bash

if [ ! -d ~/bin ];then
	echo "Warning: ~/bin does not exist; creating it ..."
	mkdir ~/bin
fi

baseDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Linking $baseDir/gist to ~/bin/gist ..."
ln -s $baseDir/gist ~/bin/gist
